---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: imla-platform
  namespace: more-demo
  labels:
    app: imla-platform
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: imla-platform
  template:
    metadata:
      labels:
        app: imla-platform
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: imla-platform-container
        image: dhavalsalwala/scalable-imla-platform:1.1.0
        imagePullPolicy: IfNotPresent
        args: ["--data_dir", "/data"]
        # resources:
        #   requests:
        #     memory: "450Mi"
        #     cpu: "207m"
        #   limits:
        #     memory: "450Mi"
        #     cpu: "207m"
        volumeMounts:
          - name: imla-platform-data
            mountPath: /data
            subPathExpr: $(POD_NAME)
          - name: imla-platform-datasets
            mountPath: /datasets
          - name: imla-platform-model
            mountPath: /model_dir
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MODELARDB_HOSTNAME
          valueFrom: 
            configMapKeyRef:
              name: modelardb-configmap
              key: MODELARDB_HOSTNAME
        - name: MODELARDB_PORT
          valueFrom:
            configMapKeyRef:
              name: modelardb-configmap
              key: MODELARDB_PORT
        - name: MODELARDB_INTERFACE
          valueFrom: 
            configMapKeyRef:
              name: modelardb-configmap
              key: MODELARDB_INTERFACE
        - name: LOGGING_LEVEL
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: LOGGING_LEVEL
        - name: RABBITMQ_USER
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_PASS
        - name: RABBITMQ_HOST
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_HOST
        - name: RABBITMQ_PORT
          valueFrom: 
            configMapKeyRef:
              name: more-configmap
              key: RABBITMQ_PORT
        - name: FORECASTING_CONSUMER_QUEUE
          valueFrom:
            configMapKeyRef:
              name: more-configmap
              key: FORECASTING_CONSUMER_QUEUE
        - name: FORECASTING_PRODUCER_QUEUE
          valueFrom:
            configMapKeyRef:
              name: more-configmap
              key: FORECASTING_PRODUCER_QUEUE

      volumes:
      - name: imla-platform-data
        nfs:
          server: master.more2020.eu
          path: /data/1/k8s/forecasting_data/trials
      - name: imla-platform-model
        nfs:
          server: master.more2020.eu
          path: /data/1/k8s/forecasting_data/model
      - name: imla-platform-datasets
        nfs:
          server: master.more2020.eu
          path: /data/1/k8s/datasets
