apiVersion: ray.io/v1alpha1
kind: RayCluster
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: ray-cluster
spec:
  rayVersion: '2.5.1'
  headGroupSpec:
    serviceType: ClusterIP
    replicas: 1
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      metadata:
        labels: {}
      spec:
        nodeSelector:
          node-role.kubernetes.io/control-plane: ""
        containers:
        - name: ray-head
          image: rayproject/ray:2.5.1-py310
          resources:
            limits:
              cpu: 16
              memory: 32Gi
            requests:
              cpu: 16
              memory: 32Gi
          ports:
          - containerPort: 6379
            name: gcs
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          volumeMounts:
            - name: ray-output
              mountPath: /data
            - mountPath: /tmp/ray
              name: ray-logs
        volumes:
          - name: ray-logs
            emptyDir: {}
          - name: ray-output
            nfs:
              server: master.more2020.eu
              path: /data/1/k8s/forecasting_data/trials

  workerGroupSpecs:
  - replicas: 5
    minReplicas: 5
    maxReplicas: 5
    groupName: group
    rayStartParams: {}
    template:
      spec:
        nodeSelector:
          node-role.kubernetes.io/worker: ""
        containers:
        - name: ray-worker
          image: rayproject/ray:2.5.1-py310
          securityContext:
            runAsUser: 0
          resources:
            limits:
              cpu: 16
              memory: 32Gi
            requests:
              cpu: 16
              memory: 32Gi
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh","-c","ray stop"]
          volumeMounts:
            - name: ray-output
              mountPath: /data
            - mountPath: /tmp/ray
              name: ray-logs
        volumes:
          - name: ray-logs
            emptyDir: {}
          - name: ray-output
            nfs:
              server: master.more2020.eu
              path: /data/1/k8s/forecasting_data/trials